### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by EarMaster** [plesk/debian11to12#1]
**Describe the bug**
During stage Pre-install packages the output stops with the following error:
```
libgcc_s.so.1 must be installed for pthread_cancel to work
```
The script continues to run, but output is stopped at that point.

[debian11to12_feedback.zip](https://github.com/plesk/debian11to12/files/15049780/debian11to12_feedback.zip)

**Comment by kpushkaryov** [comment]
That's triggered by a known issue with older Python versions: https://bugs.python.org/issue44434.
We should preload the library to prevent it.
