### ISSUE TITLE
No chrooted sftp login after upgrade

### ISSUE THREAD

**Issue by Elompenta** [plesk/debian11to12#5]
After a successful update, no sftp logon to a chrooted user subscription is possible anymore.

> Status:	Connect to host.domain.tld...
Status:	Using username "username". 
Status:	Connected to host.domain.tls
Fehler:	FATAL ERROR: Received unexpected end-of-file from SFTP server

You know about that or?
From my understanding it is a typically problem after dist upgrade with plesk and not a problem from your script. It seems that the chrooted is broken in any way. (not investigated it in detail)

I use every time this to fix this issue: https://support.plesk.com/hc/en-us/articles/12377475066391-How-to-rebuild-the-chroot-template-on-Plesk

> wget https://raw.githubusercontent.com/plesk/kb-scripts/master/update-chroot/update-chroot.sh
chmod +x update-chroot.sh
./update-chroot.sh --rebuild

After execute it, the chrooted environment works fine again.
What do you think to integrate it to the update script?

**Comment by kpushkaryov** [comment]
Thanks for reporting. The dist-upgrader runs Plesk repair procedure when finishing, but apparently that's not enough.

**Comment by vizovitin** [comment]
This will be fixed in Plesk since 18.0.65, to be released approximately on 2024-10-29.

**Comment by vizovitin** [comment]
Duplicate: https://github.com/plesk/centos2alma/issues/336
